"use client";

import { Button } from '@/components/ui/button';
import { RunStatus } from '@/services/GlobalApi';
import axios from 'axios';
import { Loader2, Search, Settings } from 'lucide-react';
import React, { useState } from 'react';
import ContentDisplay from './_components/ContentDisplay';

// Type definition for the content generated by the AI API
export type Content = {
    id: number;
    userInput: string;
    content: subContent;
    thumbnailUrl: string;
    createdOn: string;
};

// Type definition for sub-content, including titles, tags, etc.
type subContent = {
    description: string;
    image_prompts: any; // Can be typed better if you know structure
    tags: [];
    titles: [{
        seo_score: number;
        title: string;
    }];
};

/**
 * Main component for AI-based YouTube content generation.
 * This uses an input field and button to submit user prompt to the backend,
 * which in turn interacts with an AI model to generate YouTube metadata like
 * titles, descriptions, tags, and thumbnails.
 */
function AiContentGenerator() {
    // State to hold user input text
    const [userInput, setUserInput] = useState<string>();
    // State to manage loading UI state
    const [loading, setLoading] = useState(false);
    // State to store generated content after API processing
    const [content, setContent] = useState<Content>();

    /**
     * Handles the generation flow.
     * Makes POST request to /api/ai-content-generator,
     * then repeatedly polls the status using `RunStatus`
     * until it's marked as "Completed" or "Cancelled".
     */
    const onGenerate = async () => {
        try {
            setLoading(true);

            // Step 1: Send the user input to backend endpoint
            const result = await axios.post('/api/ai-content-generator', {
                userInput: userInput
            });

            console.log(result.data);

            // Step 2: Polling loop to check AI job completion status
            while (true) {
                console.log("Checking AI job status...");
                console.log(result.data.runId);

                const runStatus = await RunStatus(result.data.runId);

                console.log(runStatus);

                if (runStatus && runStatus[0]?.status == 'Completed') {
                    // AI task is done — set the content in state
                    setContent(runStatus[0]?.output[0]);
                    setLoading(false);
                    break;
                }

                if (runStatus && runStatus[0]?.status == 'Cancelled') {
                    // AI task was cancelled — exit and stop loading
                    setLoading(false);
                    break;
                }

                // Wait 1 second before polling again
                await new Promise(resolve => setTimeout(resolve, 1000));
            }
        } catch (e) {
            // In case of error — stop loading and log error
            setLoading(false);
            console.log(e);
        }
    };

    return (
        <div>
            {/* Page Header */}
            <div className='px-10 md:px-20 lg:px-40'>
                <div className='flex items-center justify-center mt-5 flex-col gap-2 '>
                    <h2 className='font-bold text-4xl'>AI Content Generator</h2>
                    <p className='text-gray-400 text-center '>
                        Generate engaging YouTube video scripts, titles, and descriptions instantly using AI. ✨
                        Boost your creativity and content output with smart, data-driven suggestions! 🎥🤖
                    </p>
                </div>

                {/* Input + Button */}
                <div className='p-2 border rounded-xl flex gap-2 items-center bg-secondary mt-5'>
                    <input
                        type='text'
                        placeholder='Enter value to generate content for your next video '
                        className='w-full p-2 outline-none bg-transparent'
                        onChange={(event) => setUserInput(event.target.value)}
                    />
                    <Button onClick={onGenerate} disabled={loading || !userInput}>
                        {loading ? <Loader2 className='animate-spin' /> : <Settings />} Generate
                    </Button>
                </div>
            </div>

            {/* Generated Content Output */}
            {/* @ts-ignore: Ignored due to typing mismatch on `content` prop */}
            <ContentDisplay content={content} loading={loading} />
        </div>
    );
}

export default AiContentGenerator;
